config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  #devise_for :sellers
  devise_for :buyers
  devise_for :sellers, controllers: { omniauth_callbacks: 'sellers/omniauth_callbacks' }
  resources :product 
  resources :announcement 

  get 'home/signup'
  get 'home/shop/:category' , to: 'home#shop', as: 'home_shop'
  get 'home/announcement/:category', to: 'home#announcement', as: 'home_announcement'
  get 'home/deca'
  get 'home/request_account_delete'

  get 'buyers/favorites'
  get 'buyers/add_favorite/:id', to: 'buyers#add_favorite', as: 'add_favorite'
  get 'buyers/remove_favorite/:id', to: 'buyers#remove_favorite', as: 'remove_favorite'

  get 'sellers/products'
  get 'sellers/add_product'
  get 'sellers/hidden_products'
  get 'sellers/hide/:id', to: 'sellers#hide', as: 'hide'
  get 'sellers/show/:id', to: 'sellers#show', as: 'show'

  get 'admin/buyers'
  get 'admin/sellers'
  get 'admin/announcements'
  get 'admin/products'
  get 'admin/add_announcement'
  get 'admin/switch/:id', to: 'admin#switch', as: 'switch'
  delete 'admin/buyer/:id', to: 'admin#admin_buyer_delete', as: 'admin_buyer_delete'
  delete 'admin/seller/:id', to: 'admin#admin_seller_delete', as: 'admin_seller_delete'

  root 'home#homepage'
end

app/models/seller.rb
# frozen_string_literal: true

class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :products, dependent: :destroy
  validates :name, presence: true
  validates :contact, presence: true
  validates :blk, presence: true
  validates :lot, presence: true
  validates :fb, presence: true
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  def products
    if seller_signed_in?
      @pagy, @records = pagy(current_seller.products.where.not(featured: 0))
    else
      redirect_to '/sellers/sign_in'
    end
  end

  def hidden_products
    if seller_signed_in?
      @pagy, @records = pagy(current_seller.products.where(featured: 0))
    else
      redirect_to '/sellers/sign_in'
    end
  end

  def hide
    if seller_signed_in?
      @to_hide = current_seller.products.where(id: params[:id])
      if @to_hide.update(featured: 0)
        flash.notice = 'Product hidden'
        redirect_to '/sellers/products'
      else
        @error = @update_product.errors.full_messages.first
        flash.alert = @error
        redirect_to '/sellers/products'
      end
    else
      redirect_to '/sellers/sign_in'
    end
  end

  def show
    if seller_signed_in?
      @to_hide = current_seller.products.where(id: params[:id])
      if @to_hide.update(featured: 1)
        flash.notice = 'Product visible'
        redirect_to '/sellers/hidden_products'
      else
        @error = @update_product.errors.full_messages.first
        flash.alert = @error
        redirect_to '/sellers/hidden_products'
      end
    else
      redirect_to '/sellers/sign_in'
    end
  end

  def add_product
    if seller_signed_in?
      @model = current_seller.products.build
    else
      redirect_to '/sellers/sign_in'
    end
  end
end

app/views/sellers/add_product.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Add Product</h2>
      </div>
    </div>
  </div>
</div>
<section class="featured spad">
  <div class="container">
    <%= form_with model: @model , url: product_index_path ,local: true do |form| %>
      <div>
        <%= form.label :name ,class:"form-label"%>
        <%= form.text_field :name ,class:"form-control" %>
      </div>
      <div>
        <%= form.label :cost ,class:"form-label"%>
        <%= form.number_field :cost ,step: 0.01,class:"form-control" %>
      </div>
      <div>
        <%= form.label :category ,class:"form-label"%>
        <%= form.select :category, ["Food", "Snacks", "Meats","Fruits","Vegetables","Drinks","Misc","Others"],{},class:"custom-select" %>
      </div>
      <div>
        <%= form.label :availability ,class:"form-label"%>
        <%= form.select :availability , ["Made upon Order", "Limited", "Daily Restock"],{},class:"custom-select"%>
      </div>
      <div>
        <%= form.label "Picture Upload" ,class:"form-label"%>
        <%= form.file_field :avatar ,class:"form-control-file", onchange:"readURL(this);"%>
      </div>
      <img id="img_prev" src="#" alt="" />
      <div>
        <%= form.label :description ,class:"form-label"%>
        <%= form.text_area :description  ,class:"form-control", size: "70x5"%>
      </div>
      <br />
      <div>
        <%= form.submit nil ,class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</section>
<!-- Assume jQuery is loaded -->
<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev')
          .attr('src', e.target.result)
          .width(100)
          .height(100);
      };

      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

app/views/sellers/hidden_products.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Hidden Products</h2>
      </div>
    </div>
  </div>
</div>

<section class="featured spad">
  <div class="container">
    <div class="row">
      <%@records.order(:id).each do |product|%>
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="featured__item">
            <div class="featured__item__pic set-bg" data-setbg=<%=url_for(product.avatar)%>>
              <ul class="featured__item__pic__hover">
                <li><a href=<%=show_path(product.id)%>><i class="fa fa-plus"></i></a></li>
                <li><a href=<%=product_path(product.id)%> data-confirm="Remove product?" rel="nofollow" data-method="delete"><i class="fa fa-trash"></i></a></li>
              </ul>
            </div>
            <div class="featured__item__text">
              <h6><a href="#"><%=product.name%></a></h6>
              <h5>₱<%=sprintf('%.2f', product.cost)%></h5>
            </div>
          </div>
        </div>
      <%end%>
    </div>
    <%= pagy_bootstrap_nav(@pagy).html_safe  %>
  </div>
</section>
<!-- Featured Section End -->

app/views/sellers/products.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Products</h2>
      </div>
    </div>
  </div>
</div>

<section class="featured spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title">
          <h2>Your Products</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="featured__item">
          <div class="featured__item__pic set-bg" data-setbg=<%=url_for(asset_path("product_image.jpg"))%>>
            <ul class="featured__item__pic__hover">
              <li><a href=<%="/sellers/add_product"%>><i class="fa fa-plus"></i></a></li>
            </ul>
          </div>
          <div class="featured__item__text">
            <h6><a href="#">Add Product</a></h6>
            <h5>₱?.??</h5>
          </div>
        </div>
      </div>
      <%@records.order(:id).each do |product|%>
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="featured__item">
            <div class="featured__item__pic set-bg" data-setbg=<%=url_for(product.avatar)%>>
              <ul class="featured__item__pic__hover">
                <li><a href=<%=product_path(product.id)%>><i class="fa fa-eye"></i></a></li>
                <li><a href=<%=edit_product_path(product.id)%>><i class="fa fa-edit"></i></a></li>
                <li><a href=<%=product_path(product.id)%> data-confirm="Remove product?" rel="nofollow" data-method="delete"><i class="fa fa-trash"></i></a></li>
              </ul>
            </div>
            <div class="featured__item__text">
              <h6><a href="#"><%=product.name%></a></h6>
              <h5>₱<%=sprintf('%.2f', product.cost)%></h5>
            </div>
          </div>
        </div>
      <%end%>
    </div>
    <%= pagy_bootstrap_nav(@pagy).html_safe  %>
  </div>
</section>
<!-- Featured Section End -->