config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  #devise_for :sellers
  devise_for :buyers
  devise_for :sellers, controllers: { omniauth_callbacks: 'sellers/omniauth_callbacks' }
  resources :product 
  resources :announcement 

  get 'home/signup'
  get 'home/shop/:category' , to: 'home#shop', as: 'home_shop'
  get 'home/announcement/:category', to: 'home#announcement', as: 'home_announcement'
  get 'home/deca'
  get 'home/request_account_delete'

  get 'buyers/favorites'
  get 'buyers/add_favorite/:id', to: 'buyers#add_favorite', as: 'add_favorite'
  get 'buyers/remove_favorite/:id', to: 'buyers#remove_favorite', as: 'remove_favorite'

  get 'sellers/products'
  get 'sellers/add_product'
  get 'sellers/hidden_products'
  get 'sellers/hide/:id', to: 'sellers#hide', as: 'hide'
  get 'sellers/show/:id', to: 'sellers#show', as: 'show'

  get 'admin/buyers'
  get 'admin/sellers'
  get 'admin/announcements'
  get 'admin/products'
  get 'admin/add_announcement'
  get 'admin/switch/:id', to: 'admin#switch', as: 'switch'
  delete 'admin/buyer/:id', to: 'admin#admin_buyer_delete', as: 'admin_buyer_delete'
  delete 'admin/seller/:id', to: 'admin#admin_seller_delete', as: 'admin_seller_delete'

  root 'home#homepage'
end

app/views/admin/add_announcement.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Add Announcement</h2>
      </div>
    </div>
  </div>
</div>
<section class="featured spad">
  <div class="container">
    <%= form_with model: Announcement , url: announcement_index_path ,local: true do |form| %>
      <div>
        <%= form.label :title ,class:"form-label"%>
        <%= form.text_field :title ,class:"form-control" %>
      </div>
      <div>
        <%= form.label :body ,class:"form-label"%>
        <%= form.text_area :body,class:"form-control", size: "70x5" %>
      </div>
      <br />
      <div>
        <%= form.submit "Create Announcement" ,class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</section>

app/views/admin/announcements.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Announcements</h2>
      </div>
    </div>
  </div>
</div>

<section class="featured spad">
  <div class="container">
    <div class="sidebar__item">
      <div class="blog__sidebar__search">
        <%= form_with   url: "/admin/announcements", method: :get ,local: true do |form| %>
        <%= form.text_field :search, placeholder: "Search..." ,class:"form-control" %>
        <%end%>
      </div>
    </div>
    <table class="table table-hover align-middle">
      <thead>
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @records.order(:id).each do |announcement| %>
          <tr>
            <td><%= announcement.title %></td>
            <td><%= announcement.category %></td>
            <td><%= link_to 'View', announcement_path(announcement.id),class:"btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_announcement_path(announcement.id),class:"btn btn-warning" %></td>
            <td><%= link_to 'Remove', announcement_path(announcement.id), method: :delete, data: { confirm: 'Remove category and all its tasks?' } ,class:"btn btn-danger"%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= pagy_bootstrap_nav(@pagy).html_safe  %>
    <br/>
    <%= link_to 'Add Announcement', admin_add_announcement_path,class:"btn btn-success" %>
  </div>
</section>

app/views/admin/buyers.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Buyers</h2>
      </div>
    </div>
  </div>
</div>

<section class="featured spad">
  <div class="container">
    <div class="sidebar__item">
      <div class="blog__sidebar__search">
        <%= form_with   url: "/admin/buyers", method: :get ,local: true do |form| %>
        <%= form.text_field :search, placeholder: "Search..." ,class:"form-control" %>
        <%end%>
      </div>
    </div>
    <table class="table table-hover align-middle">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% @records.order(:id).each do |buyer| %>
          <tr>
            <td><%= buyer.name %></td>
            <td><%= buyer.email %></td>
            <td><%= button_to "Delete", admin_buyer_delete_path(buyer.id), data: { confirm: "Are you sure?" }, method: :delete,class:"btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= pagy_bootstrap_nav(@pagy).html_safe  %>
  </div>
</section>

app/views/admin/products.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Products</h2>
      </div>
    </div>
  </div>
</div>

<section class="featured spad">
  <div class="container">
    <div class="sidebar__item">
      <div class="blog__sidebar__search">
        <%= form_with   url: "/admin/products", method: :get ,local: true do |form| %>
        <%= form.text_field :search, placeholder: "Search..." ,class:"form-control" %>
        <%end%>
      </div>
    </div>
    <table class="table table-hover align-middle">
      <thead>
        <tr>
          <th>Name</th>
          <th>Seller Email</th>
          <th>Hidden/Visible/Featured</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @records.order(:id).each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.seller.email %></td>
            <td><%= product.featured %></td>
            <td><%= link_to 'View', product_path(product.id),class:"btn btn-primary" %></td>
            <td><%= link_to 'Feature/Unfeature', switch_path(product.id),class:"btn btn-warning" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= pagy_bootstrap_nav(@pagy).html_safe  %>
  </div>
</section>

app/views/admin/sellers.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Sellers</h2>
      </div>
    </div>
  </div>
</div>

<section class="featured spad">
  <div class="container">
  <div class="sidebar__item">
    <div class="blog__sidebar__search">
      <%= form_with   url: "/admin/sellers", method: :get ,local: true do |form| %>
      <%= form.text_field :search, placeholder: "Search..." ,class:"form-control" %>
      <%end%>
    </div>
  </div>
  <table class="table table-hover align-middle">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% @records.order(:id).each do |seller| %>
        <tr>
          <td><%= seller.name %></td>
          <td><%= seller.email %></td>
          <td><%= button_to "Delete", admin_seller_delete_path(seller.id), data: { confirm: "Are you sure?" }, method: :delete,class:"btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= pagy_bootstrap_nav(@pagy).html_safe  %>
  </div>
</section>