config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  #devise_for :sellers
  devise_for :buyers
  devise_for :sellers, controllers: { omniauth_callbacks: 'sellers/omniauth_callbacks' }
  resources :product 
  resources :announcement 

  get 'home/signup'
  get 'home/shop/:category' , to: 'home#shop', as: 'home_shop'
  get 'home/announcement/:category', to: 'home#announcement', as: 'home_announcement'
  get 'home/deca'
  get 'home/request_account_delete'

  get 'buyers/favorites'
  get 'buyers/add_favorite/:id', to: 'buyers#add_favorite', as: 'add_favorite'
  get 'buyers/remove_favorite/:id', to: 'buyers#remove_favorite', as: 'remove_favorite'

  get 'sellers/products'
  get 'sellers/add_product'
  get 'sellers/hidden_products'
  get 'sellers/hide/:id', to: 'sellers#hide', as: 'hide'
  get 'sellers/show/:id', to: 'sellers#show', as: 'show'

  get 'admin/buyers'
  get 'admin/sellers'
  get 'admin/announcements'
  get 'admin/products'
  get 'admin/add_announcement'
  get 'admin/switch/:id', to: 'admin#switch', as: 'switch'
  delete 'admin/buyer/:id', to: 'admin#admin_buyer_delete', as: 'admin_buyer_delete'
  delete 'admin/seller/:id', to: 'admin#admin_seller_delete', as: 'admin_seller_delete'

  root 'home#homepage'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def homepage; end

  def shop
    if params[:search].nil?
      if params[:category] == 'All'
        @products = Product.where.not(featured: 0)
        @count = @products.count
        @pagy, @records = pagy(@products.order('name ASC, cost ASC'))
      else
        @products = Product.where(category: params[:category]).where.not(featured: 0)
        @count = @products.count
        @pagy, @records = pagy(@products.order('name ASC, cost ASC'))
      end
    else
      @products = Product.where.not(featured: 0).basic_search(params[:search])
      @count = @products.length
      @pagy, @records = pagy(@products.order('name ASC, cost ASC'))
    end
  end

  def about; end

  def request_account_delete; end
  
  def announcement
    if params[:category] == 'All'
      @pagy, @records = pagy(Announcement.all)
    else
      @count = Product.where('category' => params[:category]).count
      @pagy, @records = pagy(Announcement.where('category' => params[:category]))
    end
  end

  def deca; end
end

app/views/home/_header2.html.erb
<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
  <div class="humberger__menu__logo">
    <a href="#"><%= image_tag "logo.png" %></a>
  </div>
  <div class="humberger__menu__widget">
    <div class="header__top__right__auth">
      <%if buyer_signed_in?%>
        <a href="/buyers/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
      <% elsif seller_signed_in? %>
        <a href="/sellers/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
      <%else%>
        <a href="/buyers/sign_in"><i class="fa fa-user"></i> Login</a>
      <%end%>
    </div>
  </div>
  <nav class="humberger__menu__nav mobile-menu">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Shop", home_shop_path %></li>
      <li><a href="#">Pages</a>
        <ul class="header__menu__dropdown">
          <li><a href="./shop-details.html">About</a></li>
          <li><a href="./shoping-cart.html">Shoping Cart</a></li>
          <li><a href="./checkout.html">Check Out</a></li>
        </ul>
      </li>
      <li><a href="/home/blog.html">Announcement</a></li>
      <li><a href="/home/contact.html">Contact</a></li>
    </ul>
  </nav>
  <div id="mobile-menu-wrap"></div>
  <div class="humberger__menu__contact">
    <ul>
      <% if buyer_signed_in? %>
        <li><i class="fa fa-envelope"></i> <%= current_buyer.email %>!</li>
        <li>Welcome <%= current_buyer.name %></li>
      <% elsif seller_signed_in? %>
        <li><i class="fa fa-envelope"></i> <%= current_seller.email %>!</li>
        <li>Welcome <%= current_seller.name %></li>
      <% else  %>
        <li><i class="fa fa-envelope"></i> kadeca@gmail.com</li>
        <li>kaDECA, your one place marketplace!</li>
      <%end%>
    </ul>
  </div>
</div>
<!-- Humberger End -->
<header class="header">
  <div class="header__top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="header__top__left">
            <ul>
              <% if buyer_signed_in? %>
                <li><i class="fa fa-envelope"></i> <%= current_buyer.email %></li>
                <li>Welcome <%= current_buyer.name %>!</li>
              <% elsif seller_signed_in? %>
                <li><i class="fa fa-envelope"></i> <%= current_seller.email %>!</li>
                <li> <%= current_seller.name %><%= current_seller.contact %><%= current_seller.blk %><%= current_seller.lot %></li>
              <% else  %>
                <li><i class="fa fa-envelope"></i> kadeca@gmail.com</li>
                <li>kaDECA, your one place marketplace!</li>
              <%end%>
            </ul>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="header__top__right">
            <div class="header__top__right__social">
              <%if buyer_signed_in?%>
                <a href="/buyers/edit" ><i class="fa fa-cog"></i> Account</a>
              <% elsif seller_signed_in? %>
                <a href="/sellers/edit"><i class="fa fa-cog"></i> Account</a>
              <%else%>
                <a href="#"><i class="fa fa-facebook"></i></a>
              <%end%>
            </div>
            <div class="header__top__right__auth">
              <%if buyer_signed_in?%>
                <a href="/buyers/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
              <% elsif seller_signed_in? %>
                <a href="/sellers/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
              <%else%>
                <a href="/buyers/sign_in"><i class="fa fa-user"></i> Login</a>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="header__logo">
          <a href="/"><%= image_tag "logo.png" %></a>
        </div>
      </div>
      <div class="col-lg-9">
        <nav class="header__menu">
          <%if seller_signed_in?%>
          <ul>
            <li><%= link_to "Dashboard", root_path %></li>
            <li><%= link_to "Products", sellers_products_path %></li>
            <li><a href="/home/blog.html">Announcement</a></li>
            <li><a href="/home/contact.html">Contact</a></li>
          </ul>
          <%else%>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Shop", home_shop_path %></li>
            <li><a href="#">Pages</a>
              <ul class="header__menu__dropdown">
                <li><a href="./shop-details.html">About</a></li>
                <li><a href="./shoping-cart.html">Shoping Cart</a></li>
                <li><a href="./checkout.html">Check Out</a></li>
              </ul>
            </li>
            <li><a href="/home/blog.html">Announcement</a></li>
            <li><a href="/home/contact.html">Contact</a></li>
          </ul>
          <%end%>
          
        </nav>
      </div>
    </div>
    <div class="humberger__open">
      <i class="fa fa-bars"></i>
    </div>
  </div>
</header>

app/views/home/announcement.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Announcement</h2>
      </div>
    </div>
  </div>
</div>
<!-- Blog Section Begin -->
<section class="product spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-5">
        <div class="blog__sidebar">
          <div class="blog__sidebar__item">
            <h4>Categories</h4>
            <ul>
              <li><%= link_to "All", home_announcement_path("All") %></li>
              <% Announcement.distinct.pluck(:category).each do |announcement|%>
                <li><%= link_to announcement, home_announcement_path(announcement) %></li>
              <%end%>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-8 col-md-7">
        <div class="row">
          <% @records.order(created_at: :desc).each do |announcement|%>
            <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="blog__item">
                <div class="blog__item__text">
                  <h5><%= link_to announcement.title, announcement_path(announcement.id) %></h5>
                  <ul>
                    <li><i class="fa fa-calendar-o"></i> <%=announcement.created_at.strftime("%b %d, %Y").to_s%></li>
                    <li> <%=announcement.category%></li>
                  </ul>
                  <%= link_to "READ MORE", announcement_path(announcement.id) ,class:"blog__btn"%>
                </div>
              </div>
            </div>
          <%end%>
        </div>
        <%= pagy_bootstrap_nav(@pagy).html_safe  %>
      </div>
    </div>
  </div>
</section>
<!-- Blog Section End -->

app/views/home/deca.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Deca</h2>
      </div>
    </div>
  </div>
</div>
<section class="product spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title">
          <h2>Under Construction</h2>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/homepage.html.erb
  <!-- Title Section Begin -->
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Home</h2>
      </div>
    </div>
  </div>
</div>
<!-- Title Section End -->
<!-- Featured Section Begin -->
<section class="featured spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title">
          <h2>Featured Products</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <%Product.where(featured: 2).each do |product|%>
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="featured__item">
            <div class="featured__item__pic set-bg" data-setbg=<%=url_for(product.avatar)%>>
              <ul class="featured__item__pic__hover">
                <li><a href=<%=add_favorite_path(product.id)%>><i class="fa fa-heart"></i></a></li>
                <li><a href=<%="/product/"+product.id.to_s%>><i class="fa fa-shopping-cart"></i></a></li>
              </ul>
            </div>
            <div class="featured__item__text">
              <h6><a href="#"><%=product.name%></a></h6>
              <h5>₱<%=sprintf('%.2f', product.cost)%></h5>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>
<!-- Featured Section End -->
<!-- Blog Section Begin -->
<section class="from-blog spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title from-blog__title">
          <h2>Latest Announcements</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <%Announcement.order(created_at: :desc).limit(3).each do |announcement|%>
        <div class="col-lg-4 col-md-4 col-sm-6">
          <div class="blog__item">
            <div class="blog__item__text">
              <ul>
                <li><i class="fa fa-calendar-o"></i> <%=announcement.created_at.strftime("%b %d, %Y").to_s%></li>
              </ul>
              <h5><%= link_to announcement.title, announcement_path(announcement.id) %></h5>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>
<!-- Blog Section End -->

app/views/home/request_account_delete.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Account Deletion</h2>
      </div>
    </div>
  </div>
</div>
<section class="featured spad">
  <div class="container">
    <div class="blog__details__text">
      <h3>There are 2 ways to have your account deleted</h3>
      <b>Through account settings</b>
      <ol>
        <li>Login to your account</li>
        <li>Click on <i class="fa fa-cog"></i> Account</li>
        <li>Scroll to the bottom</li>
        <li>Click on "Cancel my account"</li>
        <li>Click "Ok"</li>
      </ol>
      <b>Send an email</b>
      <ol>
        <li>Send an email to goalista@gmail.com</li>
      </ol>
    </div>
  </div>
</section>

app/views/home/shop.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="breadcrumb__text">
        <h2>Shop</h2>
      </div>
    </div>
  </div>
</div>
<section class="product spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-5">
        <div class="sidebar">
          <div class="sidebar__item">
            <div class="blog__sidebar__search">
              <%= form_with   url: home_shop_path, method: :get ,local: true do |form| %>
              <%= form.text_field :search, placeholder: "Search..." ,class:"form-control" %>
              <%end%>
            </div>
            <h4>Category</h4>
            <ul>
              <li><%= link_to "All", home_shop_path("All") %></li>
              <% Product.distinct.pluck(:category).each do |product|%>
                <li><%= link_to product, home_shop_path(product) %></li>
              <%end%>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-9 col-md-7">
        <div class="filter__item">
          <div class="row">
            <div class="col-lg-4 col-md-5">
            </div>
            <div class="col-lg-4 col-md-4">
              <div class="filter__found">
                <h6><span><%= @count%></span> Products found</h6>
              </div>
            </div>
            <div class="col-lg-4 col-md-3">
            </div>
          </div>
        </div>
        <div class="row">
          <% @records.each do |product|%>
            <div class="col-lg-4 col-md-6 col-sm-6">
              <div class="product__item">
                <div class="product__item__pic set-bg" data-setbg=<%=url_for(product.avatar)%>>
                  <ul class="product__item__pic__hover">
                    <li><a href=<%=add_favorite_path(product.id)%>><i class="fa fa-heart"></i></a></li>
                    <li><a href=<%="/product/"+product.id.to_s%>><i class="fa fa-shopping-cart"></i></a></li>
                  </ul>
                </div>
                <div class="product__item__text">
                  <h6><a href="#"><%=product.name%></a></h6>
                  <h5>₱<%=sprintf('%.2f', product.cost)%></h5>
                </div>
              </div>
            </div>
          <%end%>
        </div>
        <%= pagy_bootstrap_nav(@pagy).html_safe  %>
      </div>
      
    </div>
  </section>