config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  #devise_for :sellers
  devise_for :buyers
  devise_for :sellers, controllers: { omniauth_callbacks: 'sellers/omniauth_callbacks' }
  resources :product 
  resources :announcement 

  get 'home/signup'
  get 'home/shop/:category' , to: 'home#shop', as: 'home_shop'
  get 'home/announcement/:category', to: 'home#announcement', as: 'home_announcement'
  get 'home/deca'
  get 'home/request_account_delete'

  get 'buyers/favorites'
  get 'buyers/add_favorite/:id', to: 'buyers#add_favorite', as: 'add_favorite'
  get 'buyers/remove_favorite/:id', to: 'buyers#remove_favorite', as: 'remove_favorite'

  get 'sellers/products'
  get 'sellers/add_product'
  get 'sellers/hidden_products'
  get 'sellers/hide/:id', to: 'sellers#hide', as: 'hide'
  get 'sellers/show/:id', to: 'sellers#show', as: 'show'

  get 'admin/buyers'
  get 'admin/sellers'
  get 'admin/announcements'
  get 'admin/products'
  get 'admin/add_announcement'
  get 'admin/switch/:id', to: 'admin#switch', as: 'switch'
  delete 'admin/buyer/:id', to: 'admin#admin_buyer_delete', as: 'admin_buyer_delete'
  delete 'admin/seller/:id', to: 'admin#admin_seller_delete', as: 'admin_seller_delete'

  root 'home#homepage'
end

app/views/layouts/_footer.html.erb
<!-- Footer Section Begin -->
<footer class="footer spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="footer__about">
          <div class="footer__about__logo">
            <%if admin_signed_in?%>
              <a href="/admin/announcements"><%= image_tag "logo2.png" %></a>
            <%elsif seller_signed_in?%>
              <a href="/sellers/products"><%= image_tag "logo2.png" %></a>
            <%else%>
              <a href="/"><%= image_tag "logo2.png" %></a>
            <%end%>
          </div>
          <ul>

          </ul>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
        <div class="footer__widget">
          <h6>Useful Links</h6>
          <ul>
            <li><a href="/sellers/sign_in">Seller Login</a></li>
            <li><a href="/admins/sign_in">Admin Login</a></li>
          </ul>
          <ul>
            <li><a href="/home/request_account_delete">Delete Account</a></li>
            <li><a href="https://www.privacypolicies.com/live/ccd223cc-23a7-4b18-bb7a-2c3e6276f95f" target="_blank">Privacy Policy</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4 col-md-12">
  
      </div>
    </div>
  </div>
</footer>
<!-- Footer Section End -->

app/views/layouts/_header2.html.erb
<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
  <div class="humberger__menu__logo">
    <%if admin_signed_in?%>
      <a href="/admin/announcements"><%= image_tag "logo.png" %></a>
    <%elsif seller_signed_in?%>
      <a href="/sellers/products"><%= image_tag "logo.png" %></a>
    <%else%>
      <a href="/"><%= image_tag "logo.png" %></a>
    <%end%>
  </div>
  <div class="humberger__menu__widget">
    <div class="header__top__right__auth">
      <%if buyer_signed_in?%>
        <a href="/buyers/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
      <% elsif seller_signed_in? %>
        <a href="/sellers/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
      <% elsif admin_signed_in? %>
        <a href="/admins/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
      <%else%>
        <a href="/buyers/sign_in"><i class="fa fa-user"></i> Login</a>
      <%end%>
    </div>
  </div>
  <nav class="humberger__menu__nav mobile-menu">
    <%if seller_signed_in?%>
      <ul>
        <li><%= link_to "Products", sellers_products_path %></li>
        <li><%= link_to "Hidden", sellers_hidden_products_path %></li>
      </ul>
    <%elsif admin_signed_in?%>
      <ul>
        <li><%= link_to "Buyers", admin_buyers_path %></li>
        <li><%= link_to "Sellers", admin_sellers_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
        <li><%= link_to "Announcements", admin_announcements_path %></li>
      </ul>
    <%else%>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Shop", home_shop_path("All") %></li>
        <li><%= link_to "Announcement", home_announcement_path("All") %></li>
        <%if buyer_signed_in?%>
          <li><%= link_to "Favorites", buyers_favorites_path %></li>
        <%end%>
      </ul>
    <%end%>
  </nav>
  <div id="mobile-menu-wrap"></div>
  <div class="header__top__right__social">
    <%if buyer_signed_in?%>
      <a href="/buyers/edit" ><i class="fa fa-cog"></i> Account</a>
    <% elsif seller_signed_in? %>
      <a href="/sellers/edit"><i class="fa fa-cog"></i> Account</a>
    <%else%>
      <a href="https://www.facebook.com/groups/215617422979575/" target="_blank"><i class="fa fa-facebook"></i></a>
    <%end%>
  </div>
  <div class="humberger__menu__contact">
    <ul>
      <% if buyer_signed_in? %>
        <li><i class="fa fa-envelope"></i> <%= current_buyer.email %>!</li>
        <li>Welcome <%= current_buyer.name %></li>
      <% elsif seller_signed_in? %>
        <li><i class="fa fa-envelope"></i> <%= current_seller.email %>!</li>
        <li>Welcome <%= current_seller.name %></li>
      <% else  %>
        <li><i class="fa fa-shopping-basket"></i> kaDECA, your one place marketplace!</li>
      <%end%>
    </ul>
  </div>
</div>
<!-- Humberger End -->
<header class="header">
  <div class="header__top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="header__top__left">
            <ul>
              <% if buyer_signed_in? %>
                <li><i class="fa fa-envelope"></i> <%= current_buyer.email %></li>
                <li>Welcome <%= current_buyer.name %>!</li>
              <% elsif seller_signed_in? %>
                <li><i class="fa fa-envelope"></i> <%= current_seller.email %></li>
                <li>Welcome <%= current_seller.name %>!</li>
              <% elsif admin_signed_in? %>
                <li><i class="fa fa-envelope"></i> <%= current_admin.email %></li>
                <li> Welcome Admin!</li>
              <% else  %>
                <li><i class="fa fa-shopping-basket"></i> kaDECA, your one place marketplace!</li>
              <%end%>
            </ul>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="header__top__right">
            <div class="header__top__right__social">
              <%if buyer_signed_in?%>
                <a href="/buyers/edit" ><i class="fa fa-cog"></i> Account</a>
              <% elsif seller_signed_in? %>
                <a href="/sellers/edit"><i class="fa fa-cog"></i> Account</a>
              <%else%>
                <a href="https://www.facebook.com/groups/215617422979575/" target="_blank"><i class="fa fa-facebook"></i></a>
              <%end%>
            </div>
            <div class="header__top__right__auth">
              <%if buyer_signed_in?%>
                <a href="/buyers/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
              <% elsif seller_signed_in? %>
                <a href="/sellers/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
              <% elsif admin_signed_in? %>
                <a href="/admins/sign_out" data-method="delete"><i class="fa fa-user"></i> Logout</a>
              <%else%>
                <a href="/buyers/sign_in"><i class="fa fa-user"></i> Login</a>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="header__logo">
          <%if admin_signed_in?%>
            <a href="/admin/announcements"><%= image_tag "logo.png" %></a>
          <%elsif seller_signed_in?%>
            <a href="/sellers/products"><%= image_tag "logo.png" %></a>
          <%else%>
            <a href="/"><%= image_tag "logo.png" %></a>
          <%end%>
        </div>
      </div>
      <div class="col-lg-9">
        <nav class="header__menu">
          <%if seller_signed_in?%>
            <ul>
              <li><%= link_to "Products", sellers_products_path %></li>
              <li><%= link_to "Hidden", sellers_hidden_products_path %></li>
            </ul>
          <%elsif admin_signed_in?%>
            <ul>
              <li><%= link_to "Buyers", admin_buyers_path %></li>
              <li><%= link_to "Sellers", admin_sellers_path %></li>
              <li><%= link_to "Products", admin_products_path %></li>
              <li><%= link_to "Announcements", admin_announcements_path %></li>
            </ul>
          <%else%>
            <ul>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Shop", home_shop_path("All") %></li>
              <li><%= link_to "Announcement", home_announcement_path("All") %></li>
              <%if buyer_signed_in?%>
                <li><%= link_to "Favorites", buyers_favorites_path %></li>
              <%end%>
            </ul>
          <%end%>
        </nav>
      </div>
    </div>
    <div class="humberger__open">
      <i class="fa fa-bars"></i>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <title>KaDECA</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application", "data-turbolinks-track" => "reload" %>
  </head>
  <body>
    <%=render "layouts/header2"%>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%=render "layouts/footer"%>
    <%= javascript_pack_tag "application2", "data-turbolinks-track" => "reload" %>
  </body>
</html>